### ISSUE TITLE
Allow renaming categories and tags

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-archive#104]
The administration panel only allows adding or deleting categories and tags. That makes it hard to rename them. You have to delete them and create new ones, and assign them again to all the torrents using them.

![image](https://github.com/torrust/torrust-index/assets/58816/ea80c903-2488-4d66-83a7-171166f1fec2)

![image](https://github.com/torrust/torrust-index/assets/58816/dad5f553-1a22-4db0-a725-ac2aceed8eb1)

**Comment by da2ce7** [comment]
I think that we should have a "duplicate" feature instead, that prompts for the name of the duplicate; then the admin can delete the old tag if they want.

**Comment by josecelano** [comment]
> I think that we should have a "duplicate" feature instead, that prompts for the name of the duplicate; then the admin can delete the old tag if they want.

Hey @da2ce7 I think that's fine for tags because torrents can have more than one tag.

I guess you mean:

- You select a tag (check box, for example)
- Then, you select the action duplicate with a text box to enter the new name
- You click duplicate, and you create the new tag. All the torrents with the previous one will also have the new one.
- Then you can delete the old tag if you want.

For categories, it's not possible because torrents can have only one category. When you duplicate a category you cannot assign the new one to the torrent because the torrent already has the one you want to rename.

If you prefer to duplicate tags and rename categories I will split a new issue for the tag duplication.

**Comment by da2ce7** [comment]
- https://github.com/torrust/torrust-index-frontend/issues/283
