### ISSUE TITLE
Show number of torrents using a tag in the `tag` administration tab

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-archive#105]
The page to handle categories shows the number of torrents using a category:

![image](https://github.com/torrust/torrust-index/assets/58816/ea80c903-2488-4d66-83a7-171166f1fec2)

But the page to edit tags does not show it:

![image](https://github.com/torrust/torrust-index/assets/58816/dad5f553-1a22-4db0-a725-ac2aceed8eb1)

I think it's a helpful feature to decide if you can remove an unused category without affecting any torrent.

You can get the number anyway by applying a filter on the URL:

- http://localhost:3001/torrents?categoryFilters=games
- http://localhost:3001/torrents?tagFilters=tag1

But I think the interface should be consistent and offer similar options if it's possible. I would keep the feature because the admin can get statistics, and there is no other way to get them now. You only can execute a database query.

**Comment by da2ce7** [comment]
- https://github.com/torrust/torrust-index-frontend/discussions/282
