### ISSUE TITLE
Add IPFS support

### ISSUE THREAD

**Issue by Zorlin** [torrust/torrust-index-archive#20]
This is a fairly big proposal, so bear with me :)

I think there's a cool opportunity to build (optional) support for IPFS into Torrust, given how young the project is. IPFS is an emerging technology for sharing and distributing files, which is sort of a blend of BitTorrent with Git and traditional web technologies.

Here's what I'm imagining - instead of "Torrent" to refer to each individual package of content on the site, we refer to them as "releases" (or something similar). The "Upload Torrent" function becomes simply "Upload", and when you go to upload something you get the additional option of pasting in an IPFS CID. The upload button would turn green upon uploading a torrent file *or* typing/pasting in a CID (or both). 

An IPFS CID is simply a piece of text that points to a particular piece of content living on IPFS (in fact, it's a hash of the content), much like a magnet link.

For example, the CID for one of my favourite albums is QmRdke7p9ZP8t4GSUxoJmFzJABRhVsWVdgtC9oMEvp7VeT - which you can stream on the web at https://ipfs.io/ipfs/QmRdke7p9ZP8t4GSUxoJmFzJABRhVsWVdgtC9oMEvp7VeT :)

I've made a quick mockup of the idea so far...

<img width="1031" alt="Screen Shot 2022-02-21 at 10 08 29 pm" src="https://user-images.githubusercontent.com/1369772/154974988-820a371a-a567-47ec-b910-d5c5f7b6e526.png">

<img width="1041" alt="Screen Shot 2022-02-21 at 10 26 50 pm" src="https://user-images.githubusercontent.com/1369772/154975016-e13a7609-3ca7-4698-9c4b-1c193707fb84.png">

When visiting the page for a release, the IPFS CID is displayed below the torrent hash (in the case of a "dual-stack" release, ie, one that lives on both BitTorrent and IPFS). A torrent-only release would look exactly like the current one. An IPFS-only release would look something like this:

![screencapture-riff-cc-torrent-1-2022-02-21-22_49_27](https://user-images.githubusercontent.com/1369772/154978188-cdeddb9b-2c6e-4e6c-a45f-2ab1b1a3f911.png)

What benefits would IPFS support bring, though?

* Global swarms for IPFS downloads - IPFS uses a global swarm by default, which means that when you download via an IPFS CID, you are downloading from everyone in the world on the IPFS network who has that content on IPFS.
* Web seeds - As IPFS-hosted files and folders are accessible via web URLs, and BitTorrent clients widely support web seeds, you can add the IPFS URL as a web seed to each torrent and automatically download from both IPFS and BitTorrent peers when you download a torrent file.
* Streaming - It's trivial to do in-browser streaming with IPFS, as you can simply stream content via a web gateway like ipfs.io. WebTorrent can also achieve this, but IPFS is a lot simpler.
* Diversity - Supporting both BitTorrent and IPFS as first-class citizens means you get the benefits of both and can benefit from both ecosystems.

It also makes it much easier to support something like federation, which I'll talk about more in a separate issue.

**Comment by cgbosse** [comment]
Hi @Zorlin  .
Thank you for your suggestion we have taken note of the issue and added it to our idea backlog for future development.

Also, stay tuned since we are going to be posting our roadmap with new issues during the coming weeks and we may need your input and help.

Thank you very much.

**Comment by josecelano** [comment]
Hi @Zorlin, I like the idea but do not know the IPFS protocol very well. I found these projects: 

- https://www.ipfs-search.com/#/ 
- https://www.ipse.io/
- 
Which are search engines. I have yet to find an index implementation like the torrust index.

**Comment by Zorlin** [comment]
I'm happy to help try to get you connected with whatever info you need if
IPFS is interesting. Since starting this thread, I've actually joined
Protocol Labs who *makes* IPFS :)
