### ISSUE TITLE
Add manual user activation

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index-archive#78]
Torrust Index should have an option for manual account activation.

Guests will then be able to signup for an account and optionally verify their email. But they won't be able to login until a Torrust Index admin activates the pending account.

**Comment by da2ce7** [comment]
Hello Mick,

I think that we should have a more comprehensive account setup process.

1. Rate Limiting captcha. +  Acceptance of Terms + (Invitation)
2. Give Account Registration Recovery Code to User.

The account recovery code is exactly the same as a password. It is generated by the client, and stored in the server as salted-hash.

3. User Password (policy optional)

4. Select Username (policy optional)

5. Add Email. (policy optional)
- Verify Email. Email Settings (Recovery + Security, Announcements, General)

- The account is in the "email" stage.  It is possible to give more privileges than just "pending or public".
(Optional Policy) This account may have an expiry, where it is deleted after a certain date.

6. Add Picture
7. Add Bio

8. Apply for Account Promotion.

If the account meets a certain policy, the user can apply for an account promotion.

A user that has the appropriate privileges can accept the promotion.  Ie. Full User.

9. Automatic Account Promotions.

The above can happen automatically according to certain administrative policies.

---

At each stage the account has a status. maybe:
- Public (no account).
- Default (no username)
- Name (username, no password)
- User (username, password)
- Mail (with email)
- Photo 
- Bio
- Full Account
- Moderator
- Administrator

- Founders (account created before a certain date)
- Adult (account older than certain amount)

Then we could have all sorts of activity based statistics connected to accounts and enable promotion requests or automatic promotions based upon these statistics.

**Comment by WarmBeer** [comment]
Hey @da2ce7 ,

I think this is a good idea. 

I'm only a bit confused by having user passwords as optional. Would users then only login with their username and/or Account Registration Recovery Code?

I'm currently working on an ERD for a new database structure that incorporates this issue as well as #30.

**Comment by da2ce7** [comment]
@WarmBeer I've updated the account_recovery_code part to be more descriptive.

**Comment by da2ce7** [comment]
- https://github.com/torrust/torrust-index-frontend/issues/284
