### ISSUE TITLE
[bug] users not getting logged out when their sessions expire

### ISSUE THREAD

**Issue by ldpr** [torrust/torrust-index-archive#82]
this is a pretty painful bug, i actually thought there was an issue open already.

in short:

1. user logs in
2. user doesn't log out and keeps the same session active for X amount of weeks
3. eventually the session will time out (_but they will still show as logged in_) and any torrents they download won't work - they show as "400 error unauthenticated" - AKA no passkey.

Having users do this:
1. Delete the torrent from the client
2. Sign out from the site
3. Sign back in again and download the torrent fresh
4. re-add new torrent - this fixes it.

This would be a _huge_ QOL improvement for us - again, thanks so much guys, you're the best

**Comment by ldpr** [comment]
should i close this and move it towards -> https://github.com/torrust/torrust-index-backend/issues ?

**Comment by BelieveInBunny** [comment]
Yep do it @ldpr 
that's what I did.
