### ISSUE TITLE
Allow banning users

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-archive#91]
I think the old frontend app (before the migration to Vue3) allowed banning users.

[The backend allows banning users](https://docs.rs/torrust-index-backend/2.0.0-alpha.2/torrust_index_backend/web/api/v1/contexts/user/index.html#ban-a-user).

We could add this feature again.

### TODO

- Create an issue on the frontend repo. The backend already supports it.

**Comment by da2ce7** [comment]
- https://github.com/torrust/torrust-index-frontend/issues/284
